import mongoose from "mongoose";

const CarSchema = new mongoose.Schema(
  {
    dealerId: mongoose.Schema.Types.ObjectId,
    userId: String,
    tag:String,
    make: { type: String, required: true }, 
    model: { type: String, required: true },
    price: Number,
    type: String,
    kms: String,
    sold: { type: Boolean, default: false },
    fuelType: String,
    fuelTankFillPrice: String,
    fuelCapacityPerTank: String,
    noOfGears: Number,
    cylinder: Number,
    features: [String],
    doors: Number,
    seats: Number,
    gearbox: String,
    images: [String],
    video: String,
    sellerComments: String,
    condition: String,
    location: String,
    modelYear: String, 
    mileage: String,
    bodyType: String,
    color: String,
    batteryRange: Number,
    chargingTime: Number,
    engineSize: Number,
    enginePower: Number,
    fuelConsumption: Number,
    isFinance: String,
    isLease: { type: Boolean, default: false },
    slug: String,
    co2Emission: Number,
    driveType: String,
    description: String,
    imageUrls: [String],
    status: { type: Number, default: 0 },
    registerationPlate: String,
    registerationExpire: String,
    unit: String,
  },
  { timestamps: true },
);

export default mongoose.models.Car || mongoose.model("Car", CarSchema);